package gov.samhsa.phr.service;

import gov.samhsa.phr.data.ccda.*;
import org.springframework.stereotype.Component;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Created by sadhana.chandra on 10/14/2015.
 */
@Component
public class IExHubDataServiceImpl implements IExHubDataService {
    public final CCDADocumentResponse GetJson()
    {
        CCDADocumentResponse tempVar = new CCDADocumentResponse();
        CCDADocumentDto doc = new CCDADocumentDto();
        tempVar.setCcdaDocuments(Arrays.asList(doc));

        // header section
        CCDAHeaderDto header = new CCDAHeaderDto();
        header.setAuthor(new Author(){{
            setOrganizationName("Org 1");}});
        header.setDocumentTypes(new String[]{"Continuity Care Document", "Consultation Note"});
        CodedConcept ccConsultNote = new CodedConcept();
        ccConsultNote.setCode("1488-4");
        ccConsultNote.setCodeSystem("2.16.840.1.113883.6.1");
        ccConsultNote.setCodeSystemName("LOINC");
        ccConsultNote.setDisplayName("Consultation Note");
        header.setCode(ccConsultNote);
        CodedConcept ccLanguage = new CodedConcept();
        ccLanguage.setCode("123456");
        ccLanguage.setCodeSystem("2.16.840.1.113883.6.96");
        ccLanguage.setCodeSystemName("SNOMEDCT");
        ccLanguage.setDisplayName("English");
        header.setLanguage(ccLanguage);
        header.setVersionNumber("1212");
        Service service = new Service();
        service.setType("service type test");
        EventDetails ed = new EventDetails();
        ed.setCondition("good");
        //ed.setStartDate(new Date);
        service.setEventDetails(ed);
        ServiceProvider sp = new ServiceProvider();
        ProviderOrganization provider = new ProviderOrganization();
        provider.setIndividualProvider("test individual provider");
        provider.setOrganization("Organization Name");
        service.setServiceProvider(new ServiceProvider[]{sp});
        header.setService(service);
        Author author = new Author();
        PersonName personName = new PersonName();
        personName.setGivenName("Henry");
        personName.setFamilyName("Ford");
        author.setName(personName);
        header.setAuthor(author);
        ContactInformation contactInformation = new ContactInformation();
        AddressDto AddressDto = new AddressDto();
        AddressDto.setCity("Columbia");
        AddressDto.setCountry("US");
        AddressDto.setStreetName1("Gateway Drive");
        AddressDto.setZipcode(21045);
        TeleCommunication tele = new TeleCommunication();
        tele.setType("Cell");
        tele.setNumber("410-555-1212");
        contactInformation.setAddress(AddressDto);
        contactInformation.setPhones(Arrays.asList(tele));
        author.setContacts(Arrays.asList(contactInformation));
        Assigned assigned = new Assigned();
        assigned.setName(personName);
        assigned.setContacts(Arrays.asList(contactInformation));
        header.setDataEnterer(assigned);
        header.setInformant(assigned);
        InformationRecipient ir = new InformationRecipient();
        ir.setName(personName);
        ir.setReceivedOrganization("Org Name 112");
        header.setInformationRecipient(ir);
        Authenticator authenticator = new Authenticator();
        authenticator.setContacts(Arrays.asList(contactInformation));
        header.setLegalAuthenticator(authenticator);
        Custodian custodian = new Custodian();
        custodian.setName("Custodian Test");
        custodian.setContact(contactInformation);
        header.setCustodian(custodian);
        DocumentationOf documentationOf = new DocumentationOf();
        Performer performer = new Performer();
        AssignedEntity assignedEntity = new AssignedEntity();
        assignedEntity.setContact(contactInformation);
        assignedEntity.setAssignedPerson(personName);
        performer.setAssignedEntity(assignedEntity);
        documentationOf.setPerformer(performer);
        RepresentedOrganization representedOrganization = new RepresentedOrganization();
        representedOrganization.setContact(contactInformation);
        ServiceEvent serviceEvent = new ServiceEvent();
        //serviceEvent.setEffectiveTimeLow();
        header.setAuthor(author);
        header.setCustodian(custodian);
        header.setDocumentationOf(documentationOf);
        DemographicInformation demographicInformation = new DemographicInformation();
        demographicInformation.setNames(Arrays.asList(personName));
        CodedConcept adminGender = new CodedConcept();
        adminGender.setCode("M");
        adminGender.setCodeSystem("2.16.840.1.113883.6.1");
        adminGender.setCodeSystemName("LOINC");
        adminGender.setDisplayName("Male");
        demographicInformation.setAdministrativeGender(adminGender);
        demographicInformation.setPatientIdentifier("123456789");
        demographicInformation.setContacts(Arrays.asList(contactInformation));
        CodedConcept maritalStatus = new CodedConcept();
        maritalStatus.setCodeSystemName("2.16.840.1.113883.6.1");
        maritalStatus.setCodeSystem("LOINC");
        maritalStatus.setCode("1488-4");
        maritalStatus.setDisplayName("Married");
        demographicInformation.setMaritalStatus(maritalStatus);
        CodedConcept race = new CodedConcept();
        maritalStatus.setCodeSystemName("2.16.840.1.113883.6.1");
        maritalStatus.setCodeSystem("LOINC");
        maritalStatus.setCode("W");
        maritalStatus.setDisplayName("White");
        demographicInformation.setRace(race);
        demographicInformation.setGuardian("Borther, Ralph Smith");
        CodedConcept ethnicity = new CodedConcept();
        ethnicity.setCodeSystemName("2.16.840.1.113883.6.1");
        ethnicity.setCodeSystem("LOINC");
        ethnicity.setCode("NH");
        ethnicity.setDisplayName("Not Hispanic or Latino");
        demographicInformation.setEthnicity(ethnicity);
        CodedConcept language = new CodedConcept();
        language.setCodeSystemName("2.16.840.1.113883.6.961");
        language.setCodeSystem("SNOWMEDCT");
        language.setCode("123456");
        language.setDisplayName("English");
        demographicInformation.setLanguages(Arrays.asList(language));
        header.setDemographicInformation(demographicInformation);
        doc.setCCDAHeader(header);

        // allergy section
        List<AllergyEntryDto> allergyList = new ArrayList<AllergyEntryDto>();
        AllergyEntryDto allergyEntry = new AllergyEntryDto();
        CodedConcept allergycc = new CodedConcept();
        allergycc.setCode("123456");
        allergycc.setCodeSystem("2.16.840.1.113883.6.96");
        allergycc.setCodeSystemName("SNOWMEDCT");
        allergycc.setDisplayName("Hives");
        CodedConcept severitycc = new CodedConcept();
        severitycc.setCode("123456");
        severitycc.setCodeSystem("2.16.840.1.113883.6.96");
        severitycc.setCodeSystemName("SNOWMEDCT");
        severitycc.setDisplayName("Mild");
        CodedConcept substancecc = new CodedConcept();
        substancecc.setCode("123456");
        substancecc.setCodeSystem("2.16.840.1.113883.6.96");
        substancecc.setCodeSystemName("SNOWMEDCT");
        substancecc.setDisplayName("Penicillin");
        CodedConcept allergySectioncc = new CodedConcept();
        allergySectioncc.setCode("1488-4");
        allergySectioncc.setCodeSystem("2.16.840.1.113883.6.1");
        allergySectioncc.setCodeSystemName("LOINC");
        allergySectioncc.setDisplayName("Alergy Section");
        allergyEntry.setName("Allergy");
        allergyEntry.setReactions(Arrays.asList(allergycc, severitycc, substancecc));
        allergyList.add(allergyEntry);
        AllergySectionDto allergySection = new AllergySectionDto();
        allergySection.setCode(allergySectioncc);
        allergySection.setNarrative("Narrative Here");
        allergySection.setTitle("Title Here");
        allergySection.setAllergies(allergyList);
        doc.setAllergySection(allergySection);

        // medication section
        MedicationSectionDto medicationSectionDto = new MedicationSectionDto();
        MedicationEntryDto medicationEntryDto = new MedicationEntryDto();
        medicationEntryDto.setName("Sertraline 20 MG/ML Oral Solution [Zoloft]");
        medicationEntryDto.setInstructions("Two times a day");
        medicationEntryDto.setStatus("Active");
        medicationEntryDto.setSig("Two times a day");
        medicationEntryDto.setType("Taking | Scheduled to Take");
        CodedConcept drugcc = new CodedConcept();
        drugcc.setCode("1488-4");
        drugcc.setCodeSystem("2.16.840.1.113883.6.88");
        drugcc.setCodeSystemName("RxNorm");
        drugcc.setDisplayName("Sertraline 20 MG/ML Oral Solution [Zoloft]");
        medicationEntryDto.setDrug(drugcc);
        CodedConcept indication1 = new CodedConcept();
        indication1.setCode("59621000");
        indication1.setCodeSystem("2.16.840.1.113883.6.96");
        indication1.setCodeSystemName("SNOMEDCT");
        indication1.setDisplayName("Test Indications 1");
        CodedConcept indication2 = new CodedConcept();
        indication2.setCode("59621000");
        indication2.setCodeSystem("2.16.840.1.113883.6.96");
        indication2.setCodeSystemName("SNOMEDCT");
        indication2.setDisplayName("Test Indications 1");
        medicationEntryDto.setIndications(Arrays.asList(indication1, indication2));
        CodedConcept reaction = new CodedConcept();
        reaction.setCode("59621000");
        reaction.setCodeSystem("2.16.840.1.113883.6.96");
        reaction.setCodeSystemName("SNOMEDCT");
        reaction.setDisplayName("Test Reaction");
        CodedConcept form = new CodedConcept();
        form.setCode("59621000");
        form.setCodeSystem("2.16.840.1.113883.6.96");
        form.setCodeSystemName("SNOMEDCT");
        form.setDisplayName("Test Form");
        CodedConcept bodySite = new CodedConcept();
        bodySite.setCode("59621000");
        bodySite.setCodeSystem("2.16.840.1.113883.6.96");
        bodySite.setCodeSystemName("Test BodySite");
        bodySite.setDisplayName("SNOMEDCT");
        CodedConcept vehicle = new CodedConcept();
        vehicle.setCode("59621000");
        vehicle.setCodeSystem("2.16.840.1.113883.6.96");
        vehicle.setCodeSystemName("SNOMEDCT");
        vehicle.setDisplayName("Test Vehicle");
        CodedConcept preCondition = new CodedConcept();
        preCondition.setCode("59621000");
        preCondition.setCodeSystem("2.16.840.1.113883.6.96");
        preCondition.setCodeSystemName("SNOMEDCT");
        preCondition.setDisplayName("Test Precondition");
        medicationEntryDto.setReaction(reaction);
        medicationEntryDto.setForm(form);
        medicationEntryDto.setBodySite(bodySite);
        medicationEntryDto.setVehicle(vehicle);
        medicationEntryDto.setPreCondition(preCondition);
        medicationEntryDto.setName("Medication");
        CodedConcept medicationSection = new CodedConcept();
        medicationSection.setCode("1488-4");
        medicationSection.setCodeSystem("2.16.840.1.113883.6.1");
        medicationSection.setCodeSystemName("LOINC");
        medicationSection.setDisplayName("Mecication Section");
        medicationSectionDto.setCode(medicationSection);
        medicationSectionDto.setNarrative("Narrative");
        medicationSectionDto.setTitle("Medication Section");
        medicationSectionDto.setMedications(Arrays.asList(medicationEntryDto));
        doc.setMedicationSection(medicationSectionDto);

        // problem section
        ProblemSectionDto problemSectionDto = new ProblemSectionDto();
        problemSectionDto.setName("Problem");
        problemSectionDto.setTitle("Problem Section");
        ProblemEntryDto problemEntryDto = new ProblemEntryDto();
        problemEntryDto.setName("Hypertension, essential");
        problemEntryDto.setStatus("Active");
        problemEntryDto.setAgeAtOnSet(31);
        CodedConcept condition = new CodedConcept();
        condition.setCode("59621000");
        condition.setCodeSystem("2.16.840.1.113883.6.96");
        condition.setCodeSystem("SNOWMEDCT");
        condition.setDisplayName("Essential hypertension (disorder)");
        problemEntryDto.setCondition(condition);
        CodedConcept type = new CodedConcept();
        type.setCode("59621000");
        type.setCodeSystem("2.16.840.1.113883.6.96");
        type.setCodeSystem("SNOWMEDCT");
        type.setDisplayName("Diagnosis");
        problemEntryDto.setType(type);
        CodedConcept healthStatus = new CodedConcept();
        healthStatus.setCode("59621000");
        healthStatus.setCodeSystem("2.16.840.1.113883.6.96");
        healthStatus.setCodeSystem("SNOWMEDCT");
        healthStatus.setDisplayName("In remission");
        problemEntryDto.setHealthStatus(healthStatus);
        problemSectionDto.setProblems(Arrays.asList(problemEntryDto));
        doc.setProblemSection(problemSectionDto);
        CodedConcept code = new CodedConcept();
        code.setCode("1488-4");
        code.setCodeSystem("2.16.840.1.113883.6.1");
        code.setCodeSystemName("LOINC");
        code.setDisplayName("Problems");
        problemSectionDto.setCode(code);
        problemSectionDto.setNarrative("Patient had Essential hypertension, it is in remission");
        problemSectionDto.setTitle("Problem Section");

        // procedure section
        ProcedureSectionDto procedureSectionDto = new ProcedureSectionDto();
        List<ProcedureEntryDto> procedureEntryDtoList = new ArrayList<ProcedureEntryDto>();
        ProcedureEntryDto procedureEntryDto1 = new ProcedureEntryDto();
        CodedConcept procedure = new CodedConcept();
        procedure.setCode("6025007");
        procedure.setCodeSystem("2.16.840.1.113883.6.96");
        procedure.setCodeSystemName("SNOMED-CT");
        procedure.setDisplayName("Laparoscopic appendectomy");
        procedureEntryDto1.setProcedure(procedure);
        procedureEntryDto1.setName("Colonic Polypectomy");
        procedureEntryDto1.setType("Procedure");
        procedureEntryDto1.setStatus("Completed");
        procedureEntryDto1.setIndications(new String[]{"Preventative", "Pre-cancerous"});
        Provider providerProcedure = new Provider();
        providerProcedure.setContact(contactInformation);
        providerProcedure.setName(personName);
        providerProcedure.setRole("Provider Role");
        procedureEntryDto1.setProviders(Arrays.asList(providerProcedure));
        procedureEntryDto1.setFacility(representedOrganization);
        procedureEntryDto1.setSpecimen("colonic polyp sample");
        procedureEntryDtoList.add(procedureEntryDto1);
        ProcedureEntryDto procedureEntryDto2 = new ProcedureEntryDto();

        CodedConcept procedure2 = new CodedConcept();
        procedure2.setCode("6025007");
        procedure2.setCodeSystem("2.16.840.1.113883.6.96");
        procedure.setCodeSystemName("SNOMED-CT");
        procedure2.setDisplayName("Nutrition education");
        procedureEntryDto2.setProcedure(procedure2);
        procedureEntryDto2.setName("Colonic Polypectomy");
        procedureEntryDto2.setType("Procedure");
        procedureEntryDto2.setStatus("Completed");
        procedureEntryDto2.setIndications(new String[]{"Preventative", "Pre-cancerous"});
        Provider providerProcedure2 = new Provider();
        providerProcedure2.setContact(contactInformation);
        providerProcedure2.setName(personName);
        providerProcedure2.setRole("Provider Role");
        procedureEntryDto1.setFacility(representedOrganization);
        procedureEntryDto1.setSpecimen("colonic polyp sample");
        procedureEntryDtoList.add(procedureEntryDto2);
        procedureSectionDto.setTitle("Procedure Title");
        procedureSectionDto.setName("Procedure");
        procedureSectionDto.setNarrative("Procedures Narrative");
        doc.setProcedureSection(procedureSectionDto);

        // results section
        ResultSectionDto resultSectionDto = new ResultSectionDto();
        ResultEntryDto resultEntryDto = new ResultEntryDto();
        resultEntryDto.setName("Blood Test");
        resultEntryDto.setSpecificTest("Hemoglobin Levels");
        resultEntryDto.setTestResults("13.2 g/dl - Normal (Ranges:13-18 g/dl)");
        resultEntryDto.setLab("Acute Care Hospital 107 Lincoln Street Worcester Massachusetts 01605");
        resultSectionDto.setResults(Arrays.asList(resultEntryDto));
        resultSectionDto.setName("Result");
        CodedConcept resultsCode = new CodedConcept();
        resultsCode.setCode("1488-4");
        resultsCode.setCodeSystem("2.16.840.1.113883.6.1");
        resultsCode.setCodeSystemName("LOINC");
        resultsCode.setDisplayName("Results");
        resultSectionDto.setCode(resultsCode);
        resultSectionDto.setNarrative("<table border=\"1\" width=\"100%\"><thead><tr><th>Substance</th><th>Reaction</th><th>Severity</th><th>Status</th></tr></thead><tbody><tr><td>Bactrim</td><td>Hives</td><td>Moderate to severe</td><td>Active</td></tr><tr><td>Aspirin</td><td>Hives</td><td>Moderate to severe</td><td>Active</td></tr></tbody></table>");
        resultSectionDto.setTitle("Results Title");
        doc.setResultSection(resultSectionDto);

        // encounters section
        EncounterSectionDto encounterSectionDto = new EncounterSectionDto();
        EncounterEntryDto encounterEntryDto = new EncounterEntryDto();
        PersonName personName2 = new PersonName();
        personName2.setGivenName("Henry");
        personName2.setFamilyName("Smith");
        Author author2 = new Author();
        author2.setName(personName2);
        author2.setContacts(Arrays.asList(contactInformation));
        encounterEntryDto.setAuthor(author2);
        CodedConcept encounterType = new CodedConcept();
        encounterType.setCode("1488-4");
        encounterType.setCodeSystem("2.16.840.1.113883.6.1");
        encounterType.setCodeSystemName("LOINC");
        encounterType.setDisplayName("Encounters Section");
        encounterEntryDto.setType(encounterType);
        CodedConcept indications = new CodedConcept();
        indications.setCode("2.16.840.1.113883.6.96");
        indications.setCodeSystem("59621000");
        indications.setCodeSystemName("SNOMEDCT");
        indications.setDisplayName("Essential hypertension (disorder)");
        encounterEntryDto.setIndications(Arrays.asList(indications));
        CodedConcept diagnosis = new CodedConcept();
        diagnosis.setCode("2.16.840.1.113883.6.96");
        diagnosis.setCodeSystem("59621000");
        diagnosis.setCodeSystemName("SNOMEDCT");
        diagnosis.setDisplayName("Essential hypertension (disorder)");
        encounterEntryDto.setDiagnosis(Arrays.asList(diagnosis));
        encounterEntryDto.setLocation(contactInformation);
        encounterEntryDto.setProviders(Arrays.asList(providerProcedure));
        encounterSectionDto.setEncounters(Arrays.asList(encounterEntryDto));
        doc.setEncounterSection(encounterSectionDto);

        // vital signs section
        VitalSignSectionDto vitalSignSectionDto = new VitalSignSectionDto();
        VitalSignEntryDto vitalSignEntryDto = new VitalSignEntryDto();
        vitalSignSectionDto.setName("Vital Sign Entry");
        vitalSignSectionDto.setNarrative("Vital Sign Narrative");
        vitalSignEntryDto.setName("Vital Sign Name");
        vitalSignEntryDto.setAuthor(author);

        Vital vital1 = new Vital();
        CodedConcept interpretation1 = new CodedConcept();
        CodedConcept vital1cc = new CodedConcept();
        vital1cc.setCode("1488-4");
        vital1cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital1cc.setCodeSystemName("LOINC");
        vital1cc.setDisplayName("RespiratoryRate");
        vital1.setValue("123");
        vital1.setUnit("/min");
        interpretation1.setCode("1488-4");
        interpretation1.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation1.setCodeSystemName("ObservationInterpretation");
        interpretation1.setDisplayName("Normal");
        vital1.setInterpretation(interpretation1);
        vital1.setType(vital1cc);

        Vital vital2 = new Vital();
        CodedConcept interpretation2 = new CodedConcept();
        CodedConcept vital2cc = new CodedConcept();
        vital2cc.setCode("1488-4");
        vital2cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital2cc.setCodeSystemName("LOINC");
        vital2cc.setDisplayName("Results");
        vital2.setValue("N");
        vital2.setUnit("/min");
        interpretation2.setCode("1488-4");
        interpretation2.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation2.setCodeSystemName("ObservationInterpretation");
        interpretation2.setDisplayName("HeartRate");
        vital2.setInterpretation(interpretation2);
        vital2.setType(vital2cc);

        Vital vital3 = new Vital();
        CodedConcept interpretation3 = new CodedConcept();
        CodedConcept vital3cc = new CodedConcept();
        vital3cc.setCode("1488-4");
        vital3cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital3cc.setCodeSystemName("LOINC");
        vital3cc.setDisplayName("O2 % BldC Oximetry");
        vital3.setValue("N");
        vital3.setUnit("/min");
        interpretation3.setCode("1488-4");
        interpretation3.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation3.setCodeSystemName("ObservationInterpretation");
        interpretation3.setDisplayName("Normal");
        vital3.setInterpretation(interpretation3);
        vital3.setType(vital3cc);

        Vital vital4 = new Vital();
        CodedConcept interpretation4 = new CodedConcept();
        CodedConcept vital4cc = new CodedConcept();
        vital4cc.setCode("1488-4");
        vital4cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital4cc.setCodeSystemName("LOINC");
        vital4cc.setDisplayName("BP Diastolic");
        vital4.setValue("N");
        vital4.setUnit("");
        interpretation4.setCode("1488-4");
        interpretation4.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation4.setCodeSystemName("ObservationInterpretation");
        interpretation4.setDisplayName("Normal");
        vital4.setInterpretation(interpretation4);
        vital4.setType(vital4cc);

        Vital vital5 = new Vital();
        CodedConcept interpretation5 = new CodedConcept();
        CodedConcept vital5cc = new CodedConcept();
        vital5cc.setCode("1488-4");
        vital5cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital5cc.setCodeSystemName("LOINC");
        vital5cc.setDisplayName("Bodytemperature");
        vital5.setValue("N");
        vital5.setUnit("cel");
        interpretation5.setCode("1488-4");
        interpretation5.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation5.setCodeSystemName("ObservationInterpretation");
        interpretation5.setDisplayName("Normal");
        vital5.setInterpretation(interpretation5);
        vital5.setType(vital5cc);

        Vital vital6 = new Vital();
        CodedConcept interpretation6 = new CodedConcept();
        CodedConcept vital6cc = new CodedConcept();
        vital6cc.setCode("1488-4");
        vital6cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital6cc.setCodeSystemName("LOINC");
        vital6cc.setDisplayName("height");
        vital6.setValue("N");
        vital6.setUnit("cm");
        interpretation6.setCode("1488-4");
        interpretation6.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation6.setCodeSystemName("ObservationInterpretation");
        interpretation6.setDisplayName("Normal");
        vital6.setInterpretation(interpretation6);
        vital6.setType(vital6cc);

        Vital vital7 = new Vital();
        CodedConcept interpretation7 = new CodedConcept();
        CodedConcept vital7cc = new CodedConcept();
        vital7cc.setCode("1488-4");
        vital7cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital7cc.setCodeSystemName("LOINC");
        vital7cc.setDisplayName("HeadCircumference");
        vital7.setValue("N");
        vital7.setUnit("cm");
        interpretation7.setCode("1488-4");
        interpretation7.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation7.setCodeSystemName("ObservationInterpretation");
        interpretation7.setDisplayName("Normal");
        vital7.setInterpretation(interpretation7);
        vital7.setType(vital7cc);

        Vital vital8 = new Vital();
        CodedConcept interpretation8 = new CodedConcept();
        CodedConcept vital8cc = new CodedConcept();
        vital8cc.setCode("1488-4");
        vital8cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital8cc.setCodeSystemName("LOINC");
        vital8cc.setDisplayName("WeightMeasured");
        vital8.setValue("N");
        vital8.setUnit("kg");
        interpretation8.setCode("1488-4");
        interpretation8.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation8.setCodeSystemName("ObservationInterpretation");
        interpretation8.setDisplayName("Normal");
        vital8.setInterpretation(interpretation8);
        vital8.setType(vital8cc);

        Vital vital9 = new Vital();
        CodedConcept interpretation9 = new CodedConcept();
        CodedConcept vital9cc = new CodedConcept();
        vital9cc.setCode("1488-4");
        vital9cc.setCodeSystem("2.16.840.1.113883.6.1");
        vital9cc.setCodeSystemName("LOINC");
        vital9cc.setDisplayName("BMI");
        vital9.setValue("N");
        vital9.setUnit("kb/m2");
        interpretation9.setCode("1488-4");
        interpretation9.setCodeSystem("2.16.840.1.113883.5.83");
        interpretation9.setCodeSystemName("ObservationInterpretation");
        interpretation9.setDisplayName("Normal");
        vital9.setInterpretation(interpretation9);
        vital9.setType(vital9cc);

        vitalSignEntryDto.setVitals(Arrays.asList(vital1, vital2, vital3, vital4, vital5, vital6, vital7, vital7, vital8, vital9));
        vitalSignSectionDto.setVitalSigns(Arrays.asList(vitalSignEntryDto));
        doc.setVitalSignSection(vitalSignSectionDto);

        // ccda document errors
        List<CCDADocumentError> errors = new ArrayList<CCDADocumentError>();
        CCDADocumentError documentError1 = new CCDADocumentError();
        documentError1.setCode("233");
        documentError1.setDescription("Section XYZ Not Found");
        CCDADocumentError documentError2 = new CCDADocumentError();
        documentError2.setCode("123");
        documentError2.setDescription("Missing Entry in Allergy Section");
        errors.add(documentError1);
        errors.add(documentError2);
        tempVar.setErrors(errors);

        return tempVar;
    }

}
